version: '3'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "/data"

  nx-app-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules